FROM golang:1.10.3 as compiler

COPY . /go/src/github.com/nats-io/gnatsd
WORKDIR /go/src/github.com/nats-io/gnatsd

RUN CGO_ENABLED=0 GOOS=linux go install -v -a -tags netgo -installsuffix netgo -ldflags "-s -w -X github.com/nats-io/gnatsd/server.gitCommit=`git rev-parse --short HEAD`"

FROM scratch
WORKDIR /
COPY --from=compiler /go/bin/gnatsd /

EXPOSE 4222 8222
ENTRYPOINT ["gnatsd"]

